import { useState } from 'react'
import { ChevronDown, ChevronUp, Download, FileJson, ExternalLink } from 'lucide-react'
import {
  RadarChart, Radar, PolarGrid, PolarAngleAxis,
  ResponsiveContainer, Tooltip,
} from 'recharts'
import type { FinalReview } from '../api'
import ScoreBar from './ScoreBar'
import RecommendationBadge from './RecommendationBadge'
import CircularScore from './CircularScore'

interface Props {
  finalReview: FinalReview
  jobId?: string
  onShowComparison?: () => void
}

const CONFIDENCE_MAP = {
  High: { cls: 'text-green-400 bg-green-900/30 border-green-800', label: 'High Confidence' },
  Medium: { cls: 'text-amber-400  bg-amber-900/30  border-amber-800', label: 'Medium Confidence' },
  Low: { cls: 'text-red-400    bg-red-900/30    border-red-900', label: 'Low Confidence' },
}

// ── Score Radar ───────────────────────────────────────────────────────────────

function ScoreRadar({ scores }: { scores: FinalReview['final_scores'] }) {
  const data = [
    { subject: 'Novelty', value: scores.novelty },
    { subject: 'Technical', value: scores.technical_soundness },
    { subject: 'Method', value: scores.methodology },
    { subject: 'Clarity', value: scores.clarity },
    { subject: 'Impact', value: scores.impact },
  ]
  return (
    <ResponsiveContainer width="100%" height={200}>
      <RadarChart data={data} margin={{ top: 8, right: 16, bottom: 8, left: 16 }}>
        <PolarGrid stroke="rgba(255,255,255,0.07)" />
        <PolarAngleAxis
          dataKey="subject"
          tick={{ fill: '#64748b', fontSize: 11, fontFamily: 'Inter' }}
        />
        <Radar
          name="Score"
          dataKey="value"
          stroke="#f59e0b"
          fill="#f59e0b"
          fillOpacity={0.15}
          strokeWidth={1.5}
        />
        <Tooltip
          contentStyle={{
            background: '#1e1b4b',
            border: '1px solid rgba(255,255,255,0.08)',
            borderRadius: 8,
            fontSize: 12,
          }}
          labelStyle={{ color: '#e2e8f0' }}
          itemStyle={{ color: '#fbbf24' }}
        />
      </RadarChart>
    </ResponsiveContainer>
  )
}

// ── Export helpers ────────────────────────────────────────────────────────────

function downloadJson(data: unknown, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

function downloadTextAsPdf(fr: FinalReview) {
  // Build a plain-text representation and open print dialog
  const lines: string[] = [
    'PaperLens — FINAL REVIEW VERDICT',
    '═'.repeat(50),
    '',
    `Recommendation: ${fr.final_recommendation}`,
    `Overall Score:  ${fr.final_scores.overall.toFixed(1)} / 10`,
    `Confidence:     ${fr.confidence}`,
    '',
    '─ SCORES ─',
    `  Novelty:             ${fr.final_scores.novelty}`,
    `  Technical Soundness: ${fr.final_scores.technical_soundness}`,
    `  Methodology:         ${fr.final_scores.methodology}`,
    `  Clarity:             ${fr.final_scores.clarity}`,
    `  Impact:              ${fr.final_scores.impact}`,
    '',
    '─ CONSOLIDATED SUMMARY ─',
    fr.consolidated_summary,
    '',
    '─ KEY STRENGTHS ─',
    ...fr.key_strengths.map((s) => `  • ${s}`),
    '',
    '─ KEY WEAKNESSES ─',
    ...fr.key_weaknesses.map((w) => `  • ${w}`),
    '',
    '─ SYNTHESIS RATIONALE ─',
    fr.synthesis_rationale,
    '',
    '─ DETAILED FEEDBACK ─',
    fr.detailed_final_feedback,
    '',
    `Generated by PaperLens on ${new Date().toLocaleDateString()}`,
  ]
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(
    `<pre style="font-family:monospace;white-space:pre-wrap;padding:2rem;max-width:800px;margin:0 auto">${lines.join('\n')}</pre>`
  )
  win.document.close()
  win.print()
}

// ── Expandable section ────────────────────────────────────────────────────────

function Section({
  title,
  defaultOpen = false,
  children,
}: {
  title: string
  defaultOpen?: boolean
  children: React.ReactNode
}) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="border border-navy-800/50 rounded-xl overflow-hidden">
      <button
        className="w-full flex items-center justify-between px-4 py-3 text-left hover:bg-navy-800/30 transition-colors"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
      >
        <span className="text-sm font-semibold text-slate-300">{title}</span>
        {open
          ? <ChevronUp className="w-4 h-4 text-slate-500" />
          : <ChevronDown className="w-4 h-4 text-slate-500" />}
      </button>
      {open && (
        <div className="px-4 pb-4 pt-1 border-t border-navy-800/40 animate-fade-in">
          {children}
        </div>
      )}
    </div>
  )
}

// ── Main component ────────────────────────────────────────────────────────────

export default function FinalVerdict({ finalReview: fr, jobId, onShowComparison }: Props) {
  const conf = CONFIDENCE_MAP[fr.confidence]

  return (
    <div className="space-y-5 animate-slide-up">
      {/* Hero card */}
      <div className="rounded-xl border border-amber-600/30 bg-gradient-to-br from-navy-900 via-navy-900 to-amber-950/20 overflow-hidden shadow-amber">
        {/* Top strip */}
        <div className="bg-amber-500/10 border-b border-amber-600/20 px-6 py-4 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <VerdictStar />
            <div>
              <p className="section-label text-amber-400/80">Final Verdict</p>
              <h2 className="text-xl font-bold text-slate-100">Consolidated Review</h2>
            </div>
          </div>
          <div className="flex items-center gap-3 flex-wrap">
            <RecommendationBadge rec={fr.final_recommendation} size="lg" />
            <span className={`inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-full border ${conf.cls}`}>
              {conf.label}
            </span>
          </div>
        </div>

        {/* Score + radar + bars */}
        <div className="p-6 grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Circular score */}
          <div className="flex flex-col items-center justify-center gap-3">
            <CircularScore value={fr.final_scores.overall} size={130} strokeWidth={9} />
            <p className="text-xs text-slate-500 text-center">Overall Score</p>
          </div>

          {/* Radar */}
          <div className="flex items-center justify-center">
            <ScoreRadar scores={fr.final_scores} />
          </div>

          {/* Dimension bars */}
          <div className="flex flex-col justify-center space-y-2.5">
            {Object.entries(fr.final_scores)
              .filter(([k]) => k !== 'overall')
              .map(([k, v]) => (
                <ScoreBar key={k} label={k} value={v as number} />
              ))}
          </div>
        </div>
      </div>

      {/* Consolidated summary */}
      <div className="card">
        <p className="section-label mb-2">Consolidated Summary</p>
        <p className="text-sm text-slate-300 leading-relaxed font-paper">
          {fr.consolidated_summary}
        </p>
      </div>

      {/* Strengths + Weaknesses side by side */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="card border-green-900/40">
          <p className="section-label text-green-500 mb-3">Key Strengths</p>
          <ul className="space-y-2">
            {fr.key_strengths.map((s, i) => (
              <li key={i} className="flex gap-2 text-sm text-slate-300">
                <span className="text-green-500 font-bold flex-shrink-0 mt-0.5">+</span>
                {s}
              </li>
            ))}
          </ul>
        </div>
        <div className="card border-red-900/40">
          <p className="section-label text-red-400 mb-3">Key Weaknesses</p>
          <ul className="space-y-2">
            {fr.key_weaknesses.map((w, i) => (
              <li key={i} className="flex gap-2 text-sm text-slate-300">
                <span className="text-red-400 font-bold flex-shrink-0 mt-0.5">−</span>
                {w}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Expandable sections */}
      <div className="space-y-2">
        <Section title="Detailed Final Feedback" defaultOpen>
          <p className="text-sm text-slate-400 leading-relaxed">{fr.detailed_final_feedback}</p>
        </Section>
        <Section title="Synthesis Rationale — How the Judge Decided">
          <p className="text-sm text-slate-400 leading-relaxed">{fr.synthesis_rationale}</p>
        </Section>
      </div>

      {/* Action bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
        <div className="flex gap-2">
          <button
            onClick={() => downloadTextAsPdf(fr)}
            className="btn-secondary text-sm gap-2"
          >
            <Download className="w-3.5 h-3.5" />
            Download PDF
          </button>
          <button
            onClick={() => downloadJson(fr, `PaperLens-verdict-${jobId ?? 'export'}.json`)}
            className="btn-secondary text-sm gap-2"
          >
            <FileJson className="w-3.5 h-3.5" />
            Download JSON
          </button>
        </div>
        {onShowComparison && (
          <button
            onClick={onShowComparison}
            className="btn-ghost text-sm"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            View Group A / B comparison
          </button>
        )}
      </div>
    </div>
  )
}

function VerdictStar() {
  return (
    <div className="w-9 h-9 rounded-xl bg-amber-500/20 border border-amber-600/30 flex items-center justify-center flex-shrink-0">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="#fbbf24" aria-hidden="true">
        <path d="M12 2l2.4 7.4H22l-6.2 4.5 2.4 7.4L12 17l-6.2 4.3 2.4-7.4L2 9.4h7.6z" />
      </svg>
    </div>
  )
}
